### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

### ISSUE THREAD

**Issue by mrgw454** [hwetters/droid64#3]
Hello,

Just pulled and built from latest source, but getting the following error when trying to run the droid64-0.9-SNAPSHOT.jar binary:

```
~/source/droid64/target$ java -jar droid64-0.9-SNAPSHOT.jar 
Failed to load DroiD64 settings. Using default settings.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at droid64.gui.MainPanel.createBookmarkMenu(MainPanel.java:737)
	at droid64.gui.MainPanel.setupMenuBar(MainPanel.java:219)
	at droid64.gui.MainPanel.<init>(MainPanel.java:193)
	at droid64.DroiD64.main(DroiD64.java:50)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 4 more

```

I'm running Debian 12 on a x64 based system.  Here's some other details:

```
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Debian-1deb12u1)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Debian-1deb12u1, mixed mode, sharing)

```

```
Apache Maven 3.8.7
Maven home: /usr/share/maven
Java version: 17.0.9, vendor: Debian, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.1.0-17-amd64", arch: "amd64", family: "unix"

```
I used the following commands to build the project:

mvn build
mvn package

While it looked like everything completed without issue, I see the following warning:

```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for droid64:droid64:jar:0.9-SNAPSHOT
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.codehaus.mojo:buildnumber-maven-plugin @ line 257, column 13
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 

```

I also downloaded the prebuilt binary and get the exact same error.

Any help you can provide would be appreciated and thank you!

**Comment by hwetters** [comment]
Hi,

JAXB is not included in openjdk since Java 9. You need to provide and 
specify some additional jar files which droid64 depends on.
Using git and maven, one way to do it is listed below:

$ git clone https://github.com/hwetters/droid64.git
$ cd droid64
$ mvn clean install -DskipTests
$ mvn dependency:build-classpath -Dmdep.outputFile=droid64.dependencies
$ java -classpath `cat 
droid64.dependencies`:target/droid64-0.9-SNAPSHOT.jar  droid64.DroiD64

This worked for me on my freshly installed Fedora 39, using a similar 
setup as yours.
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (Red_Hat-17.0.9.0.9-4) (build 17.0.9+9)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.9.0.9-4) (build 17.0.9+9, mixed 
mode, sharing)

The current binary tar.gz distribution contains a droid64.sh script file 
which sets up the classpath.

I am nearly done with the DroiD64 0.9 release, in which I have removed 
the JAXB dependency and instead made my own implementation for the 
little XML handling I needed.
So the next release will not have any mandatory dependencies. I hope. 
:-)

If you want to use the database connectivity, you still need to add the 
needed JDBC driver jar file(s). The database connectivity allows DroiD64 
to scan directories for image files and add whatever image files you are 
working with. You can also search for files and disk images it has 
recorded and easily find some program and autoload it the VICE C64 
emulator etc.

/Henrik

On 2024-01-24 18:10, mrgw454 wrote:

> Hello,
> 
> Just pulled and built from latest source, but getting the following 
> error when trying to run the droid64-0.9-SNAPSHOT.jar binary:
> 
> ~/source/droid64/target$ java -jar droid64-0.9-SNAPSHOT.jar
> Failed to load DroiD64 settings. Using default settings.
> Exception in thread "main" java.lang.NoClassDefFoundError: 
> javax/xml/bind/JAXBException
> at droid64.gui.MainPanel.createBookmarkMenu(MainPanel.java:737)
> at droid64.gui.MainPanel.setupMenuBar(MainPanel.java:219)
> at droid64.gui.MainPanel.<init>(MainPanel.java:193)
> at droid64.DroiD64.main(DroiD64.java:50)
> Caused by: java.lang.ClassNotFoundException: 
> javax.xml.bind.JAXBException
> at 
> java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
> at 
> java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
> at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
> ... 4 more
> 
> I'm running Debian 12 on a x64 based system. Here's some other details:
> 
> openjdk version "17.0.9" 2023-10-17
> OpenJDK Runtime Environment (build 17.0.9+9-Debian-1deb12u1)
> OpenJDK 64-Bit Server VM (build 17.0.9+9-Debian-1deb12u1, mixed mode, 
> sharing)
> 
> Apache Maven 3.8.7
> Maven home: /usr/share/maven
> Java version: 17.0.9, vendor: Debian, runtime: 
> /usr/lib/jvm/java-17-openjdk-amd64
> Default locale: en_US, platform encoding: UTF-8
> OS name: "linux", version: "6.1.0-17-amd64", arch: "amd64", family: 
> "unix"
> 
> I used the following commands to build the project:
> 
> mvn build
> mvn package
> 
> While it looked like everything completed without issue, I see the 
> following warning:
> 
> [INFO] Scanning for projects...
> [WARNING]
> [WARNING] Some problems were encountered while building the effective 
> model for droid64:droid64:jar:0.9-SNAPSHOT
> [WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' 
> must be unique but found duplicate declaration of plugin 
> org.codehaus.mojo:buildnumber-maven-plugin @ line 257, column 13
> [WARNING]
> [WARNING] It is highly recommended to fix these problems because they 
> threaten the stability of your build.
> [WARNING]
> [WARNING] For this reason, future Maven versions might no longer 
> support building such malformed projects.
> [WARNING]
> 
> I also downloaded the prebuilt binary and get the exact same error.
> 
> Any help you can provide would be appreciated and thank you!
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you are subscribed to this 
> thread.Message ID: ***@***.***>


Links:
------
[1] https://github.com/hwetters/droid64/issues/3
[2]

**Comment by mrgw454** [comment]
Hi Henrik,

Your instructions were great.  Application came right up!  I am interested in the in the database connectivity functionality you mentioned so I'll need to investigate how to obtain the necessary JDBC driver jar file(s) you mentioned and include that in the build process.

I'm looking forward to your next release as well.  Thanks again for all your help and the quick response!

-Ron

**Comment by hwetters** [comment]
Hi,

good to hear it worked. When you did that, maven downloaded the 
"provided" dependencies, so you also  got the JDBC drivers for 
MySQL/MariaDB, Postgresql, H2 and Firebird databases.
Start DroiD64, in the Help > DroiD64 menu it describes what is needed. 
Next go to the Settings and open the "Database" tab.

Pressing the "Database SQL" button shows an example SQL script to run on 
your database to setup what is needed. The example script has separate 
section for the various supported database vendors.
Check the "Use database" checkbox and fill in the details below (unless 
you go with the defaults fromt he example script).
Press "Test connection" if Status says "OK" you are good to go. Thern 
you have the "Search" menu at the top.

The tricky part is to setup the database and connect to it. As a Linux 
user you probably want to use either MariaDB or Postgresql.
There are many tutorials on the internet about how to get started with 
that.

Regards,

Henrik

On 2024-01-24 22:27, mrgw454 wrote:

> Hi Henrik,
> 
> Your instructions were great. Application came right up! I am 
> interested in the in the database connectivity functionality you 
> mentioned so I'll need to investigate how to obtain the necessary JDBC 
> driver jar file(s) you mentioned and include that in the build process.
> 
> I'm looking forward to your next release as well. Thanks again for all 
> your help and the quick response!
> 
> -Ron
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you commented.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/hwetters/droid64/issues/3#issuecomment-1908944769
[2]

**Comment by hwetters** [comment]
The 0.9 release has less dependencies and a classpath is setup from MANIFEST.MF in the droid64 jar file.
